### ISSUE TITLE
请教下那个小动物是怎么弄的？

### ISSUE THREAD

**Issue by ldaochen** [biezhi/ss-panel#2]

**Comment by biezhi** [comment]
emoji表情吗？

**Comment by ldaochen** [comment]
是的，看你好多个项目前面都有个漂亮的筱动物。
怎么弄的？？

**Comment by biezhi** [comment]
我的操作系统是 `mac osx` 所以按 `ctrl+command+空格` 就可以弹出emoji的表情输入，因为 github 支持 `unicode` 编码，所以你只要输入 emoji 表情或者 形如 `:smile` 都是可以的。 :smile:
